teleportSequences:
  start:
    points:
      point1:
        world: world
        x: 45.5
        y: 100
        z: 62.5
        yaw: 40.0
        pitch: 8.0
      point2:
        world: world
        x: 51.5
        y: 100
        z: 72.5
        yaw: 75.0
        pitch: 8.0

teleportSettings:
  speed: 0.5
